// File generated by FlutterFire CLI.
// Run `flutterfire configure` in this folder to replace this file with your
// real Firebase project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // Replace these placeholders after `flutterfire configure`.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1CYYu_bPlZ-FYicf-5k6NU2AYmzXC3L4',
    appId: '1:728473924781:web:5c1e906534282935050224',
    messagingSenderId: '728473924781',
    projectId: 'optimyweb-4c4b1',
    authDomain: 'optimyweb-4c4b1.firebaseapp.com',
    storageBucket: 'optimyweb-4c4b1.firebasestorage.app',
    measurementId: 'G-MPNJPX47MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1290-KFFp-MUz4dL-G3Mvil6HnYjxIg',
    appId: '1:728473924781:android:22198ce900b690d7050224',
    messagingSenderId: '728473924781',
    projectId: 'optimyweb-4c4b1',
    storageBucket: 'optimyweb-4c4b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA665zhMYlWzxSnWMx5xQG2ebyP0Eotp6E',
    appId: '1:728473924781:ios:089fc0ebadcd2912050224',
    messagingSenderId: '728473924781',
    projectId: 'optimyweb-4c4b1',
    storageBucket: 'optimyweb-4c4b1.firebasestorage.app',
    iosBundleId: 'com.optimyweb.optimyweb',
  );

  static const FirebaseOptions macos = ios;
}
